[package]
authors = ["The Rust Project Developers"]
name = "panic_unwind"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies]
libc = { version = "0.2", default-features = false }
unwind = { path = "../libunwind" }
cfg-if = "0.1.8"
