[package]
authors = ["The Rust Project Developers"]
build = "build.rs"
name = "rustc_tsan"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_tsan"
path = "lib.rs"
test = false

[dependencies]
alloc = { path = "../liballoc" }
#compiler_builtins = "0.1.0"

[build-dependencies]
build_helper = { path = "../build_helper" }
cmake = "0.1.38"
