[package]
authors = ["The Rust Project Developers"]
name = "unwind"
version = "0.0.0"
build = "build.rs"
edition = "2018"
include = [
  '/libunwind/*',
]

[lib]
name = "unwind"
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies]
libc = { version = "0.2.43", features = ['rustc-dep-of-std'], default-features = false }
cfg-if = "0.1.8"

[build-dependencies]
cc = { optional = true, version = "1.0.1" }

[features]
llvm-libunwind = ["cc"]

