[package]
name = "compiler_builtins_shim"
authors = ["The Rust Project Developers"]
version = "0.0.0"


[dependencies]
compiler_builtins = { version = "0.1.16", features = ['rustc-dep-of-std']  }

[features]
compiler-builtins-mem = ['compiler_builtins/mem']
compiler-builtins-c = ["compiler_builtins/c"]
